# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_0.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_1.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_10.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_11.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_12.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_13.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_14.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_15.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_2.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_3.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_4.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_5.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_6.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_7.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_8.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_9.0:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0